Patch 1
kbss-cvut/kbss-website pull request #13
Opened 2022-04-26 08:15 UTC by ahmadjana

this branch for our open mic sessions:
It should contains the schedule and contents of the seminars

2022-04-26 08:15 UTC, ahmadjana commented
@blcham

2022-04-26 08:17 UTC, ledsoft commented
Does it make sense to have the open mic schedule publicly visible, when the sessions are internal to KBSS? Or is there a plan to make the sessions public?

2022-04-26 21:56 UTC, blcham commented
> Does it make sense to have the open mic schedule publicly visible, when the sessions are internal to KBSS? Or is there a plan to make the sessions public?

Yes, this was the idea, see #7. I would like to publish some of the presentations and possibly invite somebody to join our presentation online.

2022-04-26 22:20 UTC, blcham reviewed
1) I don't like that we are sharing our kbss zoom channel
   - I suggest to create google meeting room for that with KBSS members beeing administrators. Thus we will be able control who comes into the room. 
2) @ledsoft  did not agree yet with the publishment of recordings ... so do you ?!
3) WRT, idea of makeing recording public ... if you think that it should not be public by default (we will of course put there only recordings that are good enough), we can do that on request (so always approve somebody who wil ask to see it -- e.g. by using google drive request permissions)

@ledsoft @ahmadjana

2022-05-04 13:29 UTC, MichalMed commented
Good thing is to have some static page with programme and link it every time like three days before.

2022-05-18 14:41 UTC, MichalMed requested changes
I'd suggest to create posts according to the one already created (JTBD). Also I think it is time to announce next weeks open mic session as a post.

2022-05-18 14:41 UTC, MichalMed commented on _pages/open_mic.md
> +## [Domain-specific Semantic Web-based Information Systems - Any Progress?](https://github.com/ahmadjana/kbss-website/blob/patch-1/_pages/seminar1.md)
use relative links

2022-05-18 14:41 UTC, MichalMed commented on _pages/seminar1.md
> +# ***[Domain-specific Semantic Web-based Information Systems - Any Progress?](https://www.researchgate.net/publication/357127663_A_Combined_Security_Ontology_based_on_the_Unified_Foundational_Ontolog
missing front matter

2022-05-18 14:41 UTC, MichalMed commented on _pages/seminar1.md
> +### *Date and Time:*   11.03.2022: 10:30 am
this is header

2022-05-18 14:41 UTC, MichalMed commented on _pages/seminar2.md
> +# ***[Collecting meaningful data: an iterative approach](https://drive.google.com/file/d/1SHU5Th5iSMbtkgR06W6w7xTzc-5pk5-k/view)***
same as seminar 1

2022-05-19 09:45 UTC, ahmadjana commented on _pages/open_mic.md
> +## [Jobs o be Done](https://kbss-cvut.github.io/kbss-website/jtbd-in-openmic)
@MichalMed  what do you mean (use the relative link?)

2022-05-23 10:31 UTC, MichalMed commented on _pages/open_mic.md
> +## [Jobs o be Done](https://kbss-cvut.github.io/kbss-website/jtbd-in-openmic)
this link points to the exact position in the internet, into your repository at github. But the webapp can be built anywhere, so use the relative link to the place where the source is located in the project, e.g. {{ "seminar2.md" | relative_link }}. MOre in the jekyll and minimal mistakes documentation

2022-05-23 11:59 UTC, closed without merging